project_params:
  version: 0.1.0

evolutionary_learning_params:
  population_size: 10
  crossover_percentage: 0.7
  mutation_percentage:
  mutation_rate:
  max_generations: 10

multiple_classification_models_params:

dynamic_ensemble_selection_params:

dataset_params:

evaluation_params:




